### ISSUE TITLE
Diodeless?

### ISSUE THREAD

**Issue by ThomasAlban** [raeedcho/chocofi-temper#12]
Is there any way this could be modified to be diodeless? I'm definitely not an expert, but it seems like there would be few enough keys on each side for there to be 1 GPIO per key (correct me if I'm wrong!)

**Comment by calerouxz** [comment]
I took a look at the schematic. I'm pretty sure the nice!view is taking some of the pins on the nice!nano, so there's no longer enough available pins to run all 18 switches per side without diodes.

**Comment by raeedcho** [comment]
Ah, yes, I couldn't remember before, but I think that's the reason I didn't make it diode-less. It could be possible to make another version of the temper without the diodes or the nice!view (or the sockets, for that matter) for a very minimal build, but it's not on my radar at the moment.

**Comment by ThomasAlban** [comment]
Ah ok makes sense. I might have a go at making this minimal version at some point, as I've been wanting to learn more about this anyway. Thanks for your help!
