### ISSUE TITLE
About securing the bottom plate

### ISSUE THREAD

**Issue by purefall0624** [raeedcho/chocofi-temper#2]
Hello! I really loves the minimalist design of your keyboard. But I'm wondering how to secure the pcb with the bottom plate, you know, about the models of the screws and maybe existing studs. Love from China!

**Comment by raeedcho** [comment]
Thanks! As I've built it in the pictures, I just used M2 screws and spacers. The screws are 3mm M2 screws, and they're attached to 5mm brass M2 spacers (also known as standoffs sometimes I think) through the PCB. The bottom plate slides over the spacers on the bottom of the PCB and secures to the spacers with the same 3mm M2 screws.

I'd love to see the result if you end up building one!

**Comment by raeedcho** [comment]
I realized that I didn't put this information in the README before--it's there now. Feel free to reopen the issue if you have more questions!
